Repository rancher/cluster-api-addon-provider-fleet, pull requests merged in 2025-04, with the labels that each got.

#239 Manually update OTEL crates
  Cargo.lock
  Cargo.toml
  justfile
  src/controllers/addon_config.rs
  src/controllers/controller.rs
  src/telemetry.rs
Labels: kind/cleanup, area/dependency

#251 Sync feature gates to ConfigMap
  config/crds/fleet-addon-config.yaml
  docs/src/02_getting_started/02_configuration.md
  justfile
  src/api/fleet_addon_config.rs
  src/controllers/addon_config.rs
  src/lib.rs
Labels: kind/feature, area/api

#259 add github token to release workflow
  .github/workflows/release.yaml
Labels: kind/bug, area/ci
